import type {
  AIAnalysisLog,
  Asset,
  CandidateScoreBreakdown,
  DailyBriefing,
  DiscoveryRun,
  EventAnalysis,
  EventCandidate,
  EventSource,
  MarketEvent,
  PaperTrade,
  RiskReview,
  TerminalData,
  TradeSetup,
} from "./types";

function scoreBreakdown(
  relevance: number,
  sourceQuality: number,
  recency: number,
  dedupeConfidence: number,
  marketContext: number,
  watchlistPreference: number,
  scanHintFit: number,
  uncertaintyPenalty: number,
): CandidateScoreBreakdown {
  return {
    relevance,
    sourceQuality,
    recency,
    dedupeConfidence,
    marketContext,
    watchlistPreference,
    scanHintFit,
    uncertaintyPenalty,
  };
}

export const demoAssets: Asset[] = [
  {
    id: "asset-race",
    ticker: "RACE",
    name: "Ferrari N.V.",
    assetType: "eu_equity",
    sector: "Luxury / Automotive",
    exchange: "NYSE / Milan",
    currency: "EUR",
    country: "Italy",
    priority: 1,
    status: "active",
    notes: "Perception-sensitive luxury brand; useful for narrative events.",
    lastMovePercent: -6.8,
    updatedAt: "2026-05-31T09:14:00.000Z",
  },
  {
    id: "asset-asml",
    ticker: "ASML",
    name: "ASML Holding",
    assetType: "eu_equity",
    sector: "Semiconductors",
    exchange: "Euronext Amsterdam / Nasdaq",
    currency: "EUR",
    country: "Netherlands",
    priority: 2,
    status: "active",
    notes: "High-impact bellwether for chip-cycle events.",
    lastMovePercent: 1.9,
    updatedAt: "2026-05-31T10:02:00.000Z",
  },
  {
    id: "asset-spy",
    ticker: "SPY",
    name: "SPDR S&P 500 ETF",
    assetType: "etf",
    sector: "Broad market",
    exchange: "NYSE Arca",
    currency: "USD",
    country: "United States",
    priority: 3,
    status: "active",
    notes: "Macro beta reference.",
    lastMovePercent: 0.5,
    updatedAt: "2026-05-31T10:41:00.000Z",
  },
  {
    id: "asset-nvo",
    ticker: "NVO",
    name: "Novo Nordisk",
    assetType: "eu_equity",
    sector: "Healthcare",
    exchange: "Copenhagen / NYSE",
    currency: "DKK",
    country: "Denmark",
    priority: 4,
    status: "active",
    notes: "Narrative sensitive around obesity-drug competition.",
    lastMovePercent: -3.4,
    updatedAt: "2026-05-31T11:20:00.000Z",
  },
];

export const demoEvents: MarketEvent[] = [
  {
    id: "event-race-launch",
    title: "Ferrari launch receives negative public reaction",
    summary:
      "New model presentation was poorly received by media and public. Stock sold off immediately, suggesting a sentiment-driven perception event.",
    source: "Manual event note",
    occurredAt: "2026-05-31T09:14:00.000Z",
    eventType: "perception",
    impactDirection: "negative",
    impactLevel: "high",
    analysisStatus: "analyzed",
    priceMovePercent: -6.8,
    linkedAssetIds: ["asset-race"],
    linkedTickers: ["RACE"],
  },
  {
    id: "event-asml-demand",
    title: "Supplier commentary improves ASML demand narrative",
    summary:
      "Supplier commentary suggests demand remains stronger than feared, supporting semiconductor momentum.",
    source: "Manual research note",
    occurredAt: "2026-05-31T10:02:00.000Z",
    eventType: "sector",
    impactDirection: "positive",
    impactLevel: "medium",
    analysisStatus: "needs_review",
    priceMovePercent: 1.9,
    linkedAssetIds: ["asset-asml"],
    linkedTickers: ["ASML"],
  },
  {
    id: "event-spy-macro",
    title: "Inflation print lands near expectations",
    summary:
      "Rates volatility cools after a near-consensus macro print, improving broad-market risk appetite.",
    source: "Manual macro note",
    occurredAt: "2026-05-31T10:41:00.000Z",
    eventType: "macro",
    impactDirection: "positive",
    impactLevel: "medium",
    analysisStatus: "analyzed",
    priceMovePercent: 0.5,
    linkedAssetIds: ["asset-spy"],
    linkedTickers: ["SPY"],
  },
];

export const demoAnalyses: EventAnalysis[] = [
  {
    id: "analysis-race-launch",
    eventId: "event-race-launch",
    sentiment: "negative",
    impactLevel: "high",
    timeHorizon: "intraday / short term",
    confidenceScore: 62,
    summary:
      "The market reaction appears negative because the product presentation damaged the short-term brand narrative. Fundamental impact is uncertain, but sentiment pressure is visible.",
    bullCase:
      "If the reaction is mostly emotional and not tied to orders or margins, the selloff may become an overreaction rebound candidate after sentiment stabilizes.",
    bearCase:
      "The event may signal broader concern about design direction, pricing power or brand confidence. Negative follow-through could continue if analysts amplify the narrative.",
    keyRisks:
      "Opening gap already extended, fundamental damage unproven, luxury-sector beta, rebound squeeze risk.",
    fundamentalImpact: "Unclear",
    sentimentImpact: "High",
    priceImpact: "Confirmed",
    reversalChance: "Possible if selling pressure fades.",
    followThroughRisk: "Elevated while media narrative remains negative.",
  },
];

export const demoSetups: TradeSetup[] = [
  {
    id: "setup-race-short",
    eventId: "event-race-launch",
    assetId: "asset-race",
    assetTicker: "RACE",
    title: "RACE possible sentiment short",
    direction: "short",
    strategy: "Sentiment short",
    entryLogic: "Only if price confirms below prior support after the first reaction.",
    stopLoss: "Close back above launch-day VWAP",
    target: "2R or prior demand zone",
    timeHorizon: "intraday / short term",
    confidenceScore: 62,
    rationale:
      "Possible short setup because the market is reacting negatively to a brand perception event and price action confirms immediate pressure.",
    invalidation:
      "Invalid if price reclaims launch-day VWAP or media narrative stabilizes before follow-through.",
    assumptions:
      "Negative perception has not been fully priced in and follow-through volume confirms the thesis.",
    status: "paper_trade",
  },
  {
    id: "setup-race-rebound",
    eventId: "event-race-launch",
    assetId: "asset-race",
    assetTicker: "RACE",
    title: "RACE overreaction rebound watch",
    direction: "long",
    strategy: "Overreaction rebound",
    entryLogic: "Only after selling pressure fades and the narrative stabilizes.",
    stopLoss: "Below capitulation low",
    target: "Mean reversion to pre-event range",
    timeHorizon: "short term",
    confidenceScore: 48,
    rationale:
      "Possible rebound if the price reaction proves exaggerated relative to fundamental damage.",
    invalidation: "Invalid if analyst downgrades or order concerns make the reaction fundamental.",
    assumptions: "The event is more reputation noise than structural brand damage.",
    status: "watching",
  },
  {
    id: "setup-asml-long",
    eventId: "event-asml-demand",
    assetId: "asset-asml",
    assetTicker: "ASML",
    title: "ASML demand narrative continuation",
    direction: "long",
    strategy: "Sector momentum",
    entryLogic: "Pullback into prior breakout zone with sector confirmation.",
    stopLoss: "Below prior support",
    target: "Retest of recent high",
    timeHorizon: "short term",
    confidenceScore: 66,
    rationale:
      "Supplier commentary could support a constructive demand revision narrative.",
    invalidation: "Invalid if broader chip sector rolls over.",
    assumptions: "Supplier commentary is representative and not already fully priced in.",
    status: "approved",
  },
];

export const demoRiskReviews: RiskReview[] = [
  {
    id: "risk-race-short",
    setupId: "setup-race-short",
    keyRisks:
      "The negative reaction is visible and may already be priced in. Shorting after a sharp opening move risks chasing.",
    counterargument:
      "Without confirmation, this can be a one-candle emotional move rather than persistent follow-through.",
    reasonToSkip:
      "Skip if price is already extended far below support or if rebound volume appears quickly.",
    riskScore: 74,
    finalVerdict: "wait",
  },
];

export const demoPaperTrades: PaperTrade[] = [
  {
    id: "trade-race-short",
    setupId: "setup-race-short",
    assetId: "asset-race",
    assetTicker: "RACE",
    direction: "short",
    entryPrice: 382.2,
    stopLoss: 392.4,
    targetPrice: 361.8,
    openedAt: "2026-05-31T09:45:00.000Z",
    closedAt: null,
    status: "open",
    exitPrice: null,
    resultPercent: 1.8,
    closeReason: null,
    notes: "Watching for follow-through confirmation after weak launch reaction.",
    hypothesisReview: null,
  },
  {
    id: "trade-asml-long",
    setupId: "setup-asml-long",
    assetId: "asset-asml",
    assetTicker: "ASML",
    direction: "long",
    entryPrice: 931,
    stopLoss: 902.5,
    targetPrice: 988,
    openedAt: "2026-05-30T13:10:00.000Z",
    closedAt: null,
    status: "open",
    exitPrice: null,
    resultPercent: -0.4,
    closeReason: null,
    notes: "Sector confirmation still needed.",
    hypothesisReview: null,
  },
  {
    id: "trade-spy-macro",
    setupId: "setup-spy-long",
    assetId: "asset-spy",
    assetTicker: "SPY",
    direction: "long",
    entryPrice: 612.4,
    stopLoss: 604.1,
    targetPrice: 628.8,
    openedAt: "2026-05-28T15:00:00.000Z",
    closedAt: "2026-05-29T18:00:00.000Z",
    status: "closed",
    exitPrice: 618.52,
    resultPercent: 1,
    closeReason: "manual_close",
    notes: "Macro reaction was constructive but not clean.",
    hypothesisReview: "Worked modestly; signal quality mixed because ETF beta masked event-specific edge.",
  },
  {
    id: "trade-old-perception",
    setupId: "setup-old-perception",
    assetId: "asset-nvo",
    assetTicker: "NVO",
    direction: "short",
    entryPrice: 131.1,
    stopLoss: 136.2,
    targetPrice: 121.8,
    openedAt: "2026-05-20T10:00:00.000Z",
    closedAt: "2026-05-22T16:00:00.000Z",
    status: "target_hit",
    exitPrice: 123.8,
    resultPercent: 5.57,
    closeReason: "target_hit",
    notes: "Competitor narrative accelerated.",
    hypothesisReview: "Strong follow-through after perception shifted into analyst concern.",
  },
];

export const demoDiscoveryRuns: DiscoveryRun[] = [
  {
    id: "run-2026-06-03-morning",
    status: "completed",
    trigger: "manual",
    provider: "mock",
    contextHints: {
      text: "RACE launch backlash, NVDA exportregels, renteverlaging, olievoorraad, crypto ETF inflows",
      mode: "ranking_boost",
      symbols: ["RACE", "NVDA", "BTC"],
      topics: ["rates", "oil", "crypto ETF"],
    },
    startedAt: "2026-06-03T08:00:00.000Z",
    completedAt: "2026-06-03T08:03:00.000Z",
    sourceCount: 10,
    candidateCount: 10,
    topCandidateCount: 10,
    errorMessage: null,
  },
];

export const demoEventSources: EventSource[] = [
  {
    id: "source-race-launch-media",
    discoveryRunId: "run-2026-06-03-morning",
    provider: "mock_broad_news",
    sourceCategory: "broad_news",
    providerItemId: "mock-news-race-001",
    sourceName: "Market media digest",
    sourceUrl: "https://example.com/race-launch-reaction",
    publishedAt: "2026-06-03T07:42:00.000Z",
    fetchedAt: "2026-06-03T08:00:20.000Z",
    rawPayloadRef: "mock://sources/race-launch-media",
    title: "Ferrari launch receives negative public reaction",
    snippet: "Media and public commentary around the launch turns negative before the open.",
    symbols: ["RACE"],
    topics: ["perception", "product_launch"],
    sourceQualityScore: 78,
  },
  {
    id: "source-tsla-refresh-cycle",
    discoveryRunId: "run-2026-06-03-morning",
    provider: "mock_broad_news",
    sourceCategory: "broad_news",
    providerItemId: "mock-news-tsla-001",
    sourceName: "Automotive news monitor",
    sourceUrl: "https://example.com/tsla-refresh-criticism",
    publishedAt: "2026-06-03T07:35:00.000Z",
    fetchedAt: "2026-06-03T08:00:34.000Z",
    rawPayloadRef: "mock://sources/tsla-refresh",
    title: "Model refresh criticism spreads through media cycle",
    snippet: "Repeated headlines point to narrative risk, but original source strength is mixed.",
    symbols: ["TSLA"],
    topics: ["perception", "auto"],
    sourceQualityScore: 61,
  },
  {
    id: "source-spy-inflation",
    discoveryRunId: "run-2026-06-03-morning",
    provider: "mock_macro_calendar",
    sourceCategory: "macro_calendar",
    providerItemId: "mock-macro-cpi-001",
    sourceName: "Macro release calendar",
    sourceUrl: "https://example.com/inflation-release",
    publishedAt: "2026-06-03T07:30:00.000Z",
    fetchedAt: "2026-06-03T08:00:38.000Z",
    rawPayloadRef: "mock://sources/inflation-print",
    title: "Inflation print cools rates volatility",
    snippet: "Macro release lands below risk threshold and eases rates volatility.",
    symbols: ["SPY"],
    topics: ["macro", "rates"],
    sourceQualityScore: 91,
  },
  {
    id: "source-asml-demand",
    discoveryRunId: "run-2026-06-03-morning",
    provider: "mock_financial_feed",
    sourceCategory: "financial_feed",
    providerItemId: "mock-feed-asml-001",
    sourceName: "Financial sentiment feed",
    sourceUrl: "https://example.com/asml-demand-note",
    publishedAt: "2026-06-03T07:22:00.000Z",
    fetchedAt: "2026-06-03T08:00:42.000Z",
    rawPayloadRef: "mock://sources/asml-demand",
    title: "Chip-equipment demand note lifts sector sentiment",
    snippet: "Sector demand commentary improves sentiment for European semiconductor equipment.",
    symbols: ["ASML"],
    topics: ["semiconductors", "sector"],
    sourceQualityScore: 84,
  },
  {
    id: "source-nvda-export",
    discoveryRunId: "run-2026-06-03-morning",
    provider: "mock_primary_source",
    sourceCategory: "primary_source",
    providerItemId: "mock-policy-nvda-001",
    sourceName: "Policy update monitor",
    sourceUrl: "https://example.com/ai-export-rules",
    publishedAt: "2026-06-03T07:15:00.000Z",
    fetchedAt: "2026-06-03T08:00:49.000Z",
    rawPayloadRef: "mock://sources/nvda-export",
    title: "Export restriction update pressures AI hardware names",
    snippet: "Policy headlines create pressure across AI hardware suppliers.",
    symbols: ["NVDA"],
    topics: ["policy", "ai_hardware"],
    sourceQualityScore: 76,
  },
  {
    id: "source-oil-supply",
    discoveryRunId: "run-2026-06-03-morning",
    provider: "mock_market_context",
    sourceCategory: "market_context",
    providerItemId: "mock-market-oil-001",
    sourceName: "Commodity movers",
    sourceUrl: "https://example.com/oil-supply-headline",
    publishedAt: "2026-06-03T07:10:00.000Z",
    fetchedAt: "2026-06-03T08:00:56.000Z",
    rawPayloadRef: "mock://sources/oil-supply",
    title: "OPEC supply headline moves energy futures pre-market",
    snippet: "Energy futures move after a supply headline, with ETF read-through.",
    symbols: ["OIL"],
    topics: ["commodity", "energy"],
    sourceQualityScore: 82,
  },
  {
    id: "source-btc-etf",
    discoveryRunId: "run-2026-06-03-morning",
    provider: "mock_financial_feed",
    sourceCategory: "financial_feed",
    providerItemId: "mock-feed-btc-001",
    sourceName: "Crypto ETF flow feed",
    sourceUrl: "https://example.com/btc-etf-flows",
    publishedAt: "2026-06-03T06:55:00.000Z",
    fetchedAt: "2026-06-03T08:01:05.000Z",
    rawPayloadRef: "mock://sources/btc-etf-flows",
    title: "ETF inflow streak slows after weekend volatility",
    snippet: "Bitcoin ETF flows slow after volatility, shifting near-term positioning.",
    symbols: ["BTC"],
    topics: ["crypto", "etf_flows"],
    sourceQualityScore: 69,
  },
  {
    id: "source-aapl-eu",
    discoveryRunId: "run-2026-06-03-morning",
    provider: "mock_primary_source",
    sourceCategory: "primary_source",
    providerItemId: "mock-eu-aapl-001",
    sourceName: "Regulatory docket",
    sourceUrl: "https://example.com/apple-eu-platform-ruling",
    publishedAt: "2026-06-03T06:44:00.000Z",
    fetchedAt: "2026-06-03T08:01:09.000Z",
    rawPayloadRef: "mock://sources/aapl-eu",
    title: "EU platform ruling adds regulatory overhang",
    snippet: "EU platform ruling adds uncertainty for large platform stocks.",
    symbols: ["AAPL"],
    topics: ["legal", "regulation"],
    sourceQualityScore: 74,
  },
  {
    id: "source-gold-yields",
    discoveryRunId: "run-2026-06-03-morning",
    provider: "mock_market_context",
    sourceCategory: "market_context",
    providerItemId: "mock-market-gld-001",
    sourceName: "Rates and metals monitor",
    sourceUrl: "https://example.com/gold-real-yields",
    publishedAt: "2026-06-03T06:30:00.000Z",
    fetchedAt: "2026-06-03T08:01:14.000Z",
    rawPayloadRef: "mock://sources/gold-yields",
    title: "Gold bid returns as real yields soften",
    snippet: "Gold bid improves while real yields soften in early trading.",
    symbols: ["GLD"],
    topics: ["macro", "real_yields"],
    sourceQualityScore: 71,
  },
  {
    id: "source-nke-margin",
    discoveryRunId: "run-2026-06-03-morning",
    provider: "mock_broad_news",
    sourceCategory: "broad_news",
    providerItemId: "mock-news-nke-001",
    sourceName: "Retail news monitor",
    sourceUrl: "https://example.com/retail-margin-warning",
    publishedAt: "2026-06-03T07:50:00.000Z",
    fetchedAt: "2026-06-03T08:01:20.000Z",
    rawPayloadRef: "mock://sources/nke-margin",
    title: "Retail margin warning echoes across apparel peers",
    snippet: "Retail margin warning may have read-through for apparel peers, but source is weak.",
    symbols: ["NKE"],
    topics: ["retail", "margin"],
    sourceQualityScore: 48,
  },
];

export const demoEventCandidates: EventCandidate[] = [
  {
    id: "candidate-race-launch",
    discoveryRunId: "run-2026-06-03-morning",
    title: "Ferrari launch receives negative public reaction",
    summary: "Product launch reaction turns negative across market media and early price context.",
    reasonToWatch: "Perception shock with strong recency and scan-hint fit.",
    affectedSymbols: ["RACE"],
    affectedMarkets: ["Luxury", "EU equities"],
    eventTypeGuess: "perception",
    impactDirectionGuess: "negative",
    impactLevelGuess: "high",
    relevanceScore: 88,
    confidenceScore: 76,
    sourceQualityScore: 78,
    recencyScore: 94,
    candidateQualityScore: 86,
    dedupeKey: "race-launch-perception-2026-06-03",
    mergeHint: null,
    candidateStatus: "new",
    ignoreReason: null,
    acceptedMarketEventId: null,
    canonicalCandidateId: null,
    sourceIds: ["source-race-launch-media"],
    rawPayloadRefs: ["mock://sources/race-launch-media"],
    scoreBreakdown: scoreBreakdown(88, 78, 94, 84, 82, 12, 18, 6),
    uncertaintyNotes: "Public reaction is visible, but fundamental impact is still unclear.",
    createdAt: "2026-06-03T08:02:00.000Z",
    updatedAt: "2026-06-03T08:02:00.000Z",
  },
  {
    id: "candidate-tsla-refresh",
    discoveryRunId: "run-2026-06-03-morning",
    title: "Model refresh criticism spreads through media cycle",
    summary: "Repeated criticism creates narrative risk, but original source strength is mixed.",
    reasonToWatch: "Narrative risk can move sentiment, but duplicate headlines need merge review.",
    affectedSymbols: ["TSLA"],
    affectedMarkets: ["US equities", "Automotive"],
    eventTypeGuess: "perception",
    impactDirectionGuess: "negative",
    impactLevelGuess: "medium",
    relevanceScore: 78,
    confidenceScore: 62,
    sourceQualityScore: 61,
    recencyScore: 88,
    candidateQualityScore: 74,
    dedupeKey: "tsla-refresh-criticism-2026-06-03",
    mergeHint: "Merge repeated criticism headlines unless a primary source confirms new info.",
    candidateStatus: "new",
    ignoreReason: null,
    acceptedMarketEventId: null,
    canonicalCandidateId: null,
    sourceIds: ["source-tsla-refresh-cycle"],
    rawPayloadRefs: ["mock://sources/tsla-refresh"],
    scoreBreakdown: scoreBreakdown(78, 61, 88, 58, 72, 4, 0, 16),
    uncertaintyNotes: "High headline repetition and weak original-source proof.",
    createdAt: "2026-06-03T08:02:04.000Z",
    updatedAt: "2026-06-03T08:02:04.000Z",
  },
  {
    id: "candidate-spy-inflation",
    discoveryRunId: "run-2026-06-03-morning",
    title: "Inflation print cools rates volatility",
    summary: "Macro release eases rates volatility and improves broad risk context.",
    reasonToWatch: "Macro regime candidate with strong primary timing and market context.",
    affectedSymbols: ["SPY"],
    affectedMarkets: ["US equities", "Rates", "Broad ETFs"],
    eventTypeGuess: "macro",
    impactDirectionGuess: "positive",
    impactLevelGuess: "high",
    relevanceScore: 84,
    confidenceScore: 82,
    sourceQualityScore: 91,
    recencyScore: 97,
    candidateQualityScore: 82,
    dedupeKey: "spy-inflation-rates-2026-06-03",
    mergeHint: null,
    candidateStatus: "new",
    ignoreReason: null,
    acceptedMarketEventId: null,
    canonicalCandidateId: null,
    sourceIds: ["source-spy-inflation"],
    rawPayloadRefs: ["mock://sources/inflation-print"],
    scoreBreakdown: scoreBreakdown(84, 91, 97, 92, 86, 8, 12, 10),
    uncertaintyNotes: "ETF beta can mask event-specific edge.",
    createdAt: "2026-06-03T08:02:08.000Z",
    updatedAt: "2026-06-03T08:02:08.000Z",
  },
  {
    id: "candidate-asml-demand",
    discoveryRunId: "run-2026-06-03-morning",
    title: "Chip-equipment demand note lifts sector sentiment",
    summary: "Financial feed and sector context point to stronger equipment demand narrative.",
    reasonToWatch: "Sector read-through with decent source quality and existing watchlist fit.",
    affectedSymbols: ["ASML"],
    affectedMarkets: ["Semiconductors", "EU equities"],
    eventTypeGuess: "sector",
    impactDirectionGuess: "positive",
    impactLevelGuess: "medium",
    relevanceScore: 80,
    confidenceScore: 75,
    sourceQualityScore: 84,
    recencyScore: 81,
    candidateQualityScore: 79,
    dedupeKey: "asml-demand-sector-2026-06-03",
    mergeHint: "Cluster related chip equipment demand notes.",
    candidateStatus: "new",
    ignoreReason: null,
    acceptedMarketEventId: null,
    canonicalCandidateId: null,
    sourceIds: ["source-asml-demand"],
    rawPayloadRefs: ["mock://sources/asml-demand"],
    scoreBreakdown: scoreBreakdown(80, 84, 81, 78, 76, 16, 0, 8),
    uncertaintyNotes: "Supplier commentary may not represent full sector demand.",
    createdAt: "2026-06-03T08:02:12.000Z",
    updatedAt: "2026-06-03T08:02:12.000Z",
  },
  {
    id: "candidate-nvda-export",
    discoveryRunId: "run-2026-06-03-morning",
    title: "Export restriction update pressures AI hardware names",
    summary: "Policy update creates pressure across AI hardware suppliers.",
    reasonToWatch: "Policy shock candidate with scan-hint fit and sector-wide read-through.",
    affectedSymbols: ["NVDA"],
    affectedMarkets: ["AI hardware", "US semiconductors"],
    eventTypeGuess: "legal",
    impactDirectionGuess: "negative",
    impactLevelGuess: "high",
    relevanceScore: 82,
    confidenceScore: 70,
    sourceQualityScore: 76,
    recencyScore: 90,
    candidateQualityScore: 77,
    dedupeKey: "nvda-export-restriction-2026-06-03",
    mergeHint: null,
    candidateStatus: "new",
    ignoreReason: null,
    acceptedMarketEventId: null,
    canonicalCandidateId: null,
    sourceIds: ["source-nvda-export"],
    rawPayloadRefs: ["mock://sources/nvda-export"],
    scoreBreakdown: scoreBreakdown(82, 76, 90, 80, 79, 8, 17, 13),
    uncertaintyNotes: "Policy details still need primary confirmation.",
    createdAt: "2026-06-03T08:02:16.000Z",
    updatedAt: "2026-06-03T08:02:16.000Z",
  },
  {
    id: "candidate-oil-supply",
    discoveryRunId: "run-2026-06-03-morning",
    title: "OPEC supply headline moves energy futures pre-market",
    summary: "Energy futures react to a supply headline with potential ETF read-through.",
    reasonToWatch: "Commodity catalyst with visible market context.",
    affectedSymbols: ["OIL", "XLE"],
    affectedMarkets: ["Energy", "Commodities"],
    eventTypeGuess: "macro",
    impactDirectionGuess: "mixed",
    impactLevelGuess: "medium",
    relevanceScore: 73,
    confidenceScore: 72,
    sourceQualityScore: 82,
    recencyScore: 73,
    candidateQualityScore: 75,
    dedupeKey: "oil-opec-supply-2026-06-03",
    mergeHint: "Merge with later inventory headlines if same supply driver.",
    candidateStatus: "new",
    ignoreReason: null,
    acceptedMarketEventId: null,
    canonicalCandidateId: null,
    sourceIds: ["source-oil-supply"],
    rawPayloadRefs: ["mock://sources/oil-supply"],
    scoreBreakdown: scoreBreakdown(73, 82, 73, 76, 88, 0, 14, 10),
    uncertaintyNotes: "Commodity moves can reverse quickly after inventory details.",
    createdAt: "2026-06-03T08:02:20.000Z",
    updatedAt: "2026-06-03T08:02:20.000Z",
  },
  {
    id: "candidate-btc-etf",
    discoveryRunId: "run-2026-06-03-morning",
    title: "ETF inflow streak slows after weekend volatility",
    summary: "Bitcoin ETF inflows slow after volatility, creating positioning risk.",
    reasonToWatch: "Positioning shift with scan-hint fit, but source quality is moderate.",
    affectedSymbols: ["BTC"],
    affectedMarkets: ["Crypto", "ETF flows"],
    eventTypeGuess: "sector",
    impactDirectionGuess: "mixed",
    impactLevelGuess: "medium",
    relevanceScore: 70,
    confidenceScore: 66,
    sourceQualityScore: 69,
    recencyScore: 86,
    candidateQualityScore: 72,
    dedupeKey: "btc-etf-inflow-slowdown-2026-06-03",
    mergeHint: null,
    candidateStatus: "new",
    ignoreReason: null,
    acceptedMarketEventId: null,
    canonicalCandidateId: null,
    sourceIds: ["source-btc-etf"],
    rawPayloadRefs: ["mock://sources/btc-etf-flows"],
    scoreBreakdown: scoreBreakdown(70, 69, 86, 72, 75, 0, 18, 13),
    uncertaintyNotes: "ETF flow data can lag and crypto volatility can dominate.",
    createdAt: "2026-06-03T08:02:24.000Z",
    updatedAt: "2026-06-03T08:02:24.000Z",
  },
  {
    id: "candidate-aapl-eu",
    discoveryRunId: "run-2026-06-03-morning",
    title: "EU platform ruling adds regulatory overhang",
    summary: "Regulatory ruling adds uncertainty around platform economics.",
    reasonToWatch: "Legal catalyst for large-cap platform risk.",
    affectedSymbols: ["AAPL"],
    affectedMarkets: ["Mega-cap tech", "EU regulation"],
    eventTypeGuess: "legal",
    impactDirectionGuess: "negative",
    impactLevelGuess: "medium",
    relevanceScore: 68,
    confidenceScore: 64,
    sourceQualityScore: 74,
    recencyScore: 70,
    candidateQualityScore: 69,
    dedupeKey: "aapl-eu-platform-ruling-2026-06-03",
    mergeHint: null,
    candidateStatus: "new",
    ignoreReason: null,
    acceptedMarketEventId: null,
    canonicalCandidateId: null,
    sourceIds: ["source-aapl-eu"],
    rawPayloadRefs: ["mock://sources/aapl-eu"],
    scoreBreakdown: scoreBreakdown(68, 74, 70, 80, 70, 0, 0, 11),
    uncertaintyNotes: "Legal impact may be slow-moving and not immediately tradable.",
    createdAt: "2026-06-03T08:02:28.000Z",
    updatedAt: "2026-06-03T08:02:28.000Z",
  },
  {
    id: "candidate-gld-yields",
    discoveryRunId: "run-2026-06-03-morning",
    title: "Gold bid returns as real yields soften",
    summary: "Gold improves as real yields soften, suggesting macro hedge demand.",
    reasonToWatch: "Macro hedge candidate, useful as context for rates-sensitive trades.",
    affectedSymbols: ["GLD"],
    affectedMarkets: ["Metals", "Rates"],
    eventTypeGuess: "macro",
    impactDirectionGuess: "positive",
    impactLevelGuess: "medium",
    relevanceScore: 63,
    confidenceScore: 62,
    sourceQualityScore: 71,
    recencyScore: 68,
    candidateQualityScore: 66,
    dedupeKey: "gld-real-yields-2026-06-03",
    mergeHint: null,
    candidateStatus: "new",
    ignoreReason: null,
    acceptedMarketEventId: null,
    canonicalCandidateId: null,
    sourceIds: ["source-gold-yields"],
    rawPayloadRefs: ["mock://sources/gold-yields"],
    scoreBreakdown: scoreBreakdown(63, 71, 68, 86, 74, 0, 0, 9),
    uncertaintyNotes: "Macro context item more than standalone equity catalyst.",
    createdAt: "2026-06-03T08:02:32.000Z",
    updatedAt: "2026-06-03T08:02:32.000Z",
  },
  {
    id: "candidate-nke-margin",
    discoveryRunId: "run-2026-06-03-morning",
    title: "Retail margin warning echoes across apparel peers",
    summary: "Potential apparel peer read-through, but source quality is weak.",
    reasonToWatch: "Weak-source candidate worth ignoring unless confirmed.",
    affectedSymbols: ["NKE"],
    affectedMarkets: ["Retail", "Apparel"],
    eventTypeGuess: "sector",
    impactDirectionGuess: "negative",
    impactLevelGuess: "low",
    relevanceScore: 58,
    confidenceScore: 42,
    sourceQualityScore: 48,
    recencyScore: 83,
    candidateQualityScore: 51,
    dedupeKey: "nke-retail-margin-warning-2026-06-03",
    mergeHint: "Needs primary confirmation before analysis.",
    candidateStatus: "new",
    ignoreReason: null,
    acceptedMarketEventId: null,
    canonicalCandidateId: null,
    sourceIds: ["source-nke-margin"],
    rawPayloadRefs: ["mock://sources/nke-margin"],
    scoreBreakdown: scoreBreakdown(58, 48, 83, 50, 55, 0, 0, 26),
    uncertaintyNotes: "Weak-source candidate; likely ignore unless corroborated.",
    createdAt: "2026-06-03T08:02:36.000Z",
    updatedAt: "2026-06-03T08:02:36.000Z",
  },
];

export const demoAiLogs: AIAnalysisLog[] = [
  {
    id: "log-discovery-ranking",
    analysisType: "candidate_ranking",
    provider: "mock",
    model: "mock-discovery-v1",
    promptVersion: "candidate-ranking-v1",
    status: "success",
    usefulnessRating: 4,
    summary: "Ranked 10 candidate events into a top 10 using source quality, recency and dedupe.",
    sourcePayloadRefs: demoEventSources.map((source) => source.rawPayloadRef).filter(Boolean) as string[],
    scoreInputs: { sourceCount: 10, candidateCount: 10, topCandidateCount: 10 },
    createdAt: "2026-06-03T08:03:00.000Z",
  },
  {
    id: "log-race-analysis",
    analysisType: "event_analysis",
    provider: "mock",
    model: "mock-analysis-v1",
    promptVersion: "event-analysis-v1",
    status: "success",
    usefulnessRating: 4,
    summary: "Generated perception event analysis for RACE.",
    sourcePayloadRefs: ["mock://sources/race-launch-media"],
    scoreInputs: { candidateQualityScore: 86 },
    createdAt: "2026-05-31T09:18:00.000Z",
  },
  {
    id: "log-race-risk",
    analysisType: "risk_review",
    provider: "mock",
    model: "mock-risk-v1",
    promptVersion: "risk-review-v1",
    status: "success",
    usefulnessRating: 5,
    summary: "Flagged chasing and priced-in risks for RACE short.",
    sourcePayloadRefs: [],
    scoreInputs: { riskScore: 74 },
    createdAt: "2026-05-31T09:22:00.000Z",
  },
];

export const demoDailyBriefing: DailyBriefing = {
  id: "briefing-2026-05-31",
  briefingDate: "2026-05-31",
  title: "Daily Market Briefing",
  marketSummary:
    "Risk appetite is selective. Semiconductors remain constructive, broad ETFs are stable, and luxury sentiment is weaker.",
  keyEvents: [
    "RACE perception event deserves review before any short thesis.",
    "ASML demand narrative improved but still needs sector confirmation.",
    "SPY macro context is supportive but not a high-edge setup by itself.",
  ],
  possibleSetups: [
    "RACE possible sentiment short only after follow-through confirmation.",
    "ASML long continuation on pullback with sector support.",
  ],
  keyRisks: [
    "Opening gaps can already price in the event.",
    "Perception events can reverse quickly after emotional selling.",
  ],
  openTrades: ["RACE short watch", "ASML long watch"],
  doNothingWarning:
    "Avoid chasing opening gaps without confirmation and defined invalidation.",
  conclusion:
    "Observe first. RACE is worth tracking, not trading blindly. ASML needs a cleaner entry.",
};

export const demoTerminalData: TerminalData = {
  discoveryRuns: demoDiscoveryRuns,
  eventSources: demoEventSources,
  eventCandidates: demoEventCandidates,
  latestDiscoveryRun: demoDiscoveryRuns[0],
  assets: demoAssets,
  events: demoEvents,
  analyses: demoAnalyses,
  setups: demoSetups,
  riskReviews: demoRiskReviews,
  paperTrades: demoPaperTrades,
  aiLogs: demoAiLogs,
  dailyBriefing: demoDailyBriefing,
  isDemoMode: true,
};
