import type {
  AIAnalysisLog,
  Asset,
  DailyBriefing,
  EventAnalysis,
  MarketEvent,
  PaperTrade,
  RiskReview,
  TerminalData,
  TradeSetup,
} from "./types";

export const demoAssets: Asset[] = [
  {
    id: "asset-race",
    ticker: "RACE",
    name: "Ferrari N.V.",
    assetType: "eu_equity",
    sector: "Luxury / Automotive",
    exchange: "NYSE / Milan",
    currency: "EUR",
    country: "Italy",
    priority: 1,
    status: "active",
    notes: "Perception-sensitive luxury brand; useful for narrative events.",
    lastMovePercent: -6.8,
    updatedAt: "2026-05-31T09:14:00.000Z",
  },
  {
    id: "asset-asml",
    ticker: "ASML",
    name: "ASML Holding",
    assetType: "eu_equity",
    sector: "Semiconductors",
    exchange: "Euronext Amsterdam / Nasdaq",
    currency: "EUR",
    country: "Netherlands",
    priority: 2,
    status: "active",
    notes: "High-impact bellwether for chip-cycle events.",
    lastMovePercent: 1.9,
    updatedAt: "2026-05-31T10:02:00.000Z",
  },
  {
    id: "asset-spy",
    ticker: "SPY",
    name: "SPDR S&P 500 ETF",
    assetType: "etf",
    sector: "Broad market",
    exchange: "NYSE Arca",
    currency: "USD",
    country: "United States",
    priority: 3,
    status: "active",
    notes: "Macro beta reference.",
    lastMovePercent: 0.5,
    updatedAt: "2026-05-31T10:41:00.000Z",
  },
  {
    id: "asset-nvo",
    ticker: "NVO",
    name: "Novo Nordisk",
    assetType: "eu_equity",
    sector: "Healthcare",
    exchange: "Copenhagen / NYSE",
    currency: "DKK",
    country: "Denmark",
    priority: 4,
    status: "active",
    notes: "Narrative sensitive around obesity-drug competition.",
    lastMovePercent: -3.4,
    updatedAt: "2026-05-31T11:20:00.000Z",
  },
];

export const demoEvents: MarketEvent[] = [
  {
    id: "event-race-launch",
    title: "Ferrari launch receives negative public reaction",
    summary:
      "New model presentation was poorly received by media and public. Stock sold off immediately, suggesting a sentiment-driven perception event.",
    source: "Manual event note",
    occurredAt: "2026-05-31T09:14:00.000Z",
    eventType: "perception",
    impactDirection: "negative",
    impactLevel: "high",
    analysisStatus: "analyzed",
    priceMovePercent: -6.8,
    linkedAssetIds: ["asset-race"],
    linkedTickers: ["RACE"],
  },
  {
    id: "event-asml-demand",
    title: "Supplier commentary improves ASML demand narrative",
    summary:
      "Supplier commentary suggests demand remains stronger than feared, supporting semiconductor momentum.",
    source: "Manual research note",
    occurredAt: "2026-05-31T10:02:00.000Z",
    eventType: "sector",
    impactDirection: "positive",
    impactLevel: "medium",
    analysisStatus: "needs_review",
    priceMovePercent: 1.9,
    linkedAssetIds: ["asset-asml"],
    linkedTickers: ["ASML"],
  },
  {
    id: "event-spy-macro",
    title: "Inflation print lands near expectations",
    summary:
      "Rates volatility cools after a near-consensus macro print, improving broad-market risk appetite.",
    source: "Manual macro note",
    occurredAt: "2026-05-31T10:41:00.000Z",
    eventType: "macro",
    impactDirection: "positive",
    impactLevel: "medium",
    analysisStatus: "analyzed",
    priceMovePercent: 0.5,
    linkedAssetIds: ["asset-spy"],
    linkedTickers: ["SPY"],
  },
];

export const demoAnalyses: EventAnalysis[] = [
  {
    id: "analysis-race-launch",
    eventId: "event-race-launch",
    sentiment: "negative",
    impactLevel: "high",
    timeHorizon: "intraday / short term",
    confidenceScore: 62,
    summary:
      "The market reaction appears negative because the product presentation damaged the short-term brand narrative. Fundamental impact is uncertain, but sentiment pressure is visible.",
    bullCase:
      "If the reaction is mostly emotional and not tied to orders or margins, the selloff may become an overreaction rebound candidate after sentiment stabilizes.",
    bearCase:
      "The event may signal broader concern about design direction, pricing power or brand confidence. Negative follow-through could continue if analysts amplify the narrative.",
    keyRisks:
      "Opening gap already extended, fundamental damage unproven, luxury-sector beta, rebound squeeze risk.",
    fundamentalImpact: "Unclear",
    sentimentImpact: "High",
    priceImpact: "Confirmed",
    reversalChance: "Possible if selling pressure fades.",
    followThroughRisk: "Elevated while media narrative remains negative.",
  },
];

export const demoSetups: TradeSetup[] = [
  {
    id: "setup-race-short",
    eventId: "event-race-launch",
    assetId: "asset-race",
    assetTicker: "RACE",
    title: "RACE possible sentiment short",
    direction: "short",
    strategy: "Sentiment short",
    entryLogic: "Only if price confirms below prior support after the first reaction.",
    stopLoss: "Close back above launch-day VWAP",
    target: "2R or prior demand zone",
    timeHorizon: "intraday / short term",
    confidenceScore: 62,
    rationale:
      "Possible short setup because the market is reacting negatively to a brand perception event and price action confirms immediate pressure.",
    invalidation:
      "Invalid if price reclaims launch-day VWAP or media narrative stabilizes before follow-through.",
    assumptions:
      "Negative perception has not been fully priced in and follow-through volume confirms the thesis.",
    status: "paper_trade",
  },
  {
    id: "setup-race-rebound",
    eventId: "event-race-launch",
    assetId: "asset-race",
    assetTicker: "RACE",
    title: "RACE overreaction rebound watch",
    direction: "long",
    strategy: "Overreaction rebound",
    entryLogic: "Only after selling pressure fades and the narrative stabilizes.",
    stopLoss: "Below capitulation low",
    target: "Mean reversion to pre-event range",
    timeHorizon: "short term",
    confidenceScore: 48,
    rationale:
      "Possible rebound if the price reaction proves exaggerated relative to fundamental damage.",
    invalidation: "Invalid if analyst downgrades or order concerns make the reaction fundamental.",
    assumptions: "The event is more reputation noise than structural brand damage.",
    status: "watching",
  },
  {
    id: "setup-asml-long",
    eventId: "event-asml-demand",
    assetId: "asset-asml",
    assetTicker: "ASML",
    title: "ASML demand narrative continuation",
    direction: "long",
    strategy: "Sector momentum",
    entryLogic: "Pullback into prior breakout zone with sector confirmation.",
    stopLoss: "Below prior support",
    target: "Retest of recent high",
    timeHorizon: "short term",
    confidenceScore: 66,
    rationale:
      "Supplier commentary could support a constructive demand revision narrative.",
    invalidation: "Invalid if broader chip sector rolls over.",
    assumptions: "Supplier commentary is representative and not already fully priced in.",
    status: "approved",
  },
];

export const demoRiskReviews: RiskReview[] = [
  {
    id: "risk-race-short",
    setupId: "setup-race-short",
    keyRisks:
      "The negative reaction is visible and may already be priced in. Shorting after a sharp opening move risks chasing.",
    counterargument:
      "Without confirmation, this can be a one-candle emotional move rather than persistent follow-through.",
    reasonToSkip:
      "Skip if price is already extended far below support or if rebound volume appears quickly.",
    riskScore: 74,
    finalVerdict: "wait",
  },
];

export const demoPaperTrades: PaperTrade[] = [
  {
    id: "trade-race-short",
    setupId: "setup-race-short",
    assetId: "asset-race",
    assetTicker: "RACE",
    direction: "short",
    entryPrice: 382.2,
    stopLoss: 392.4,
    targetPrice: 361.8,
    openedAt: "2026-05-31T09:45:00.000Z",
    closedAt: null,
    status: "open",
    exitPrice: null,
    resultPercent: 1.8,
    closeReason: null,
    notes: "Watching for follow-through confirmation after weak launch reaction.",
    hypothesisReview: null,
  },
  {
    id: "trade-asml-long",
    setupId: "setup-asml-long",
    assetId: "asset-asml",
    assetTicker: "ASML",
    direction: "long",
    entryPrice: 931,
    stopLoss: 902.5,
    targetPrice: 988,
    openedAt: "2026-05-30T13:10:00.000Z",
    closedAt: null,
    status: "open",
    exitPrice: null,
    resultPercent: -0.4,
    closeReason: null,
    notes: "Sector confirmation still needed.",
    hypothesisReview: null,
  },
  {
    id: "trade-spy-macro",
    setupId: "setup-spy-long",
    assetId: "asset-spy",
    assetTicker: "SPY",
    direction: "long",
    entryPrice: 612.4,
    stopLoss: 604.1,
    targetPrice: 628.8,
    openedAt: "2026-05-28T15:00:00.000Z",
    closedAt: "2026-05-29T18:00:00.000Z",
    status: "closed",
    exitPrice: 618.52,
    resultPercent: 1,
    closeReason: "manual_close",
    notes: "Macro reaction was constructive but not clean.",
    hypothesisReview: "Worked modestly; signal quality mixed because ETF beta masked event-specific edge.",
  },
  {
    id: "trade-old-perception",
    setupId: "setup-old-perception",
    assetId: "asset-nvo",
    assetTicker: "NVO",
    direction: "short",
    entryPrice: 131.1,
    stopLoss: 136.2,
    targetPrice: 121.8,
    openedAt: "2026-05-20T10:00:00.000Z",
    closedAt: "2026-05-22T16:00:00.000Z",
    status: "target_hit",
    exitPrice: 123.8,
    resultPercent: 5.57,
    closeReason: "target_hit",
    notes: "Competitor narrative accelerated.",
    hypothesisReview: "Strong follow-through after perception shifted into analyst concern.",
  },
];

export const demoAiLogs: AIAnalysisLog[] = [
  {
    id: "log-race-analysis",
    analysisType: "event_analysis",
    provider: "mock",
    model: "mock-analysis-v1",
    promptVersion: "event-analysis-v1",
    status: "success",
    usefulnessRating: 4,
    summary: "Generated perception event analysis for RACE.",
    createdAt: "2026-05-31T09:18:00.000Z",
  },
  {
    id: "log-race-risk",
    analysisType: "risk_review",
    provider: "mock",
    model: "mock-risk-v1",
    promptVersion: "risk-review-v1",
    status: "success",
    usefulnessRating: 5,
    summary: "Flagged chasing and priced-in risks for RACE short.",
    createdAt: "2026-05-31T09:22:00.000Z",
  },
];

export const demoDailyBriefing: DailyBriefing = {
  id: "briefing-2026-05-31",
  briefingDate: "2026-05-31",
  title: "Daily Market Briefing",
  marketSummary:
    "Risk appetite is selective. Semiconductors remain constructive, broad ETFs are stable, and luxury sentiment is weaker.",
  keyEvents: [
    "RACE perception event deserves review before any short thesis.",
    "ASML demand narrative improved but still needs sector confirmation.",
    "SPY macro context is supportive but not a high-edge setup by itself.",
  ],
  possibleSetups: [
    "RACE possible sentiment short only after follow-through confirmation.",
    "ASML long continuation on pullback with sector support.",
  ],
  keyRisks: [
    "Opening gaps can already price in the event.",
    "Perception events can reverse quickly after emotional selling.",
  ],
  openTrades: ["RACE short watch", "ASML long watch"],
  doNothingWarning:
    "Avoid chasing opening gaps without confirmation and defined invalidation.",
  conclusion:
    "Observe first. RACE is worth tracking, not trading blindly. ASML needs a cleaner entry.",
};

export const demoTerminalData: TerminalData = {
  assets: demoAssets,
  events: demoEvents,
  analyses: demoAnalyses,
  setups: demoSetups,
  riskReviews: demoRiskReviews,
  paperTrades: demoPaperTrades,
  aiLogs: demoAiLogs,
  dailyBriefing: demoDailyBriefing,
  isDemoMode: true,
};
